import Head from 'next/head'
import Image from 'next/image'
import Stories from '../components/Stories';
import NewsFeed from '../components/NewsFeed';
import NewsFeedSideBar from '../components/NewsFeedSideBar';





export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
          <Stories/>
          <div className="sm:flex justify-center sm:pt-5 sm:p-5 space-x-0 sm:space-x-10 ">
            <NewsFeed/>
            <NewsFeedSideBar/>
          </div>
      </main>
    </div>
  )
}
